[build]
builder = "nixpacks"
python = "3.9"

[deploy]
startCommand = "python -c \"import os, sys; os.chdir('backend'); sys.path.insert(0, '/app/backend'); from main import app; import uvicorn; uvicorn.run(app, host='0.0.0.0', port=int(os.getenv('PORT', '8000')))\""
healthcheckPath = "/healthz"
healthcheckTimeout = 45
restartPolicyType = "ON_FAILURE"
min_instances = 1

[variables]
PYTHONUNBUFFERED = "1" 