[build]
builder = "nixpacks"
python = "3.9"

[deploy]
startCommand = "python -c \"import os; port = int(os.getenv('PORT', '8000')); from main import app; import uvicorn; uvicorn.run(app, host='0.0.0.0', port=port)\""
healthcheckPath = "/healthz"
healthcheckTimeout = 45
restartPolicyType = "ON_FAILURE"
min_instances = 1

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1" 