[build]
builder = "nixpacks"
python = "3.9"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/healthz"
healthcheckTimeout = 45
restartPolicyType = "ON_FAILURE"
min_instances = 1

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1" 