[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x backend/start.sh && backend/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PYTHON_VERSION = "3.9"
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1" 