[build]
builder = "nixpacks"
python = "3.9"

[deploy]
startCommand = "cd backend && PYTHONPATH=/app/backend python -m uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
healthcheckPath = "/healthz"
healthcheckTimeout = 45
restartPolicyType = "ON_FAILURE"
min_instances = 1

[variables]
PYTHONUNBUFFERED = "1" 