services:
  # Backend API Service
  - type: web
    name: immi-ai-backend
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1
      - key: PINECONE_INDEX_NAME
        value: visaindex
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://immi-ai-frontend.onrender.com,http://localhost:3000
    healthCheckPath: /healthz
    autoDeploy: true

  # Frontend Next.js Service
  - type: web
    name: immi-ai-frontend
    env: node
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NEXT_PUBLIC_API_URL
        value: https://immi-ai-backend.onrender.com
    autoDeploy: true 